import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from model_config import MODEL_NAME, MODEL_PARAMETER_SIZE, MODEL_PROVIDER, MODEL_ROLE, MAX_TOKENS, TEMPERATURE
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'output'
LOG = ROOT / 'logging'
outs = sorted(OUT.glob('EC_*.json'))
if not outs:
    print('no outputs')
    sys.exit(1)

meta = {
    'model': MODEL_NAME,
    'parameters': MODEL_PARAMETER_SIZE,
    'provider': MODEL_PROVIDER,
    'role': MODEL_ROLE,
    'generation_parameters': {'temperature': TEMPERATURE, 'max_tokens': MAX_TOKENS},
    'framework':'python',
    'runtime':sys.platform,
    'execution_note': 'This submission was generated by deterministic CSV policy rules; the configured local model was not invoked during this run.'
}
# write trace
with (LOG / 'trace.jsonl').open('w', encoding='utf-8') as f:
    for p in outs:
        o = json.loads(p.read_text(encoding='utf-8'))
        f.write(json.dumps({'case_id': o.get('case_id'), 'status':'processed'}) + '\n')
# write metadata at root and logging
(ROOT / 'metadata.json').write_text(json.dumps(meta, indent=2), encoding='utf-8')
(LOG / 'metadata.json').write_text(json.dumps(meta, indent=2), encoding='utf-8')
print('wrote', len(outs))
